# Generated by Django 4.2.4 on 2023-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
